applicationName: ladesa-ro-web

deployment:
  replicas: 1
  enabled: true

  image:
    repository: ghcr.io/ifro-jipa/cronos-app/front-end
    tag: main
    pullPolicy: Always

  # imagePullSecrets:
  #   - name: cronos-registry-pull-secret

  containerSecurityContext:
    runAsNonRoot: false
    readOnlyRootFilesystem: false

  ports:
    - containerPort: 80
      name: web-port

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  # envFrom:
  #   web-config:
  #     type: secret
  #     name: cronos-front-end-web

  resources:
    limits:
      memory: '2Gi'
      cpu: '2'
    requests:
      cpu: '50m'
      memory: '1Gi'

  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 10
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 15
  startupProbe:
    httpGet:
      path: /
      port: 80
    failureThreshold: 30
    periodSeconds: 10

service:
  enabled: true
  type: NodePort
  ports:
    - name: web-service
      port: 80
      targetPort: web-port

ingress:
  enabled: true
  hosts:
    - host: 'cronos.pulselab.jetspace.dev'
      paths:
        - path: /
          pathType: ImplementationSpecific
          servicePort: web-service
